'use client'

import { CheckCircle, Shield, Clock } from 'lucide-react'

interface AnswerDisplayProps {
  answer: {
    question: string
    answer: string
    signature: string
    timestamp: number
  }
}

export function AnswerDisplay({ answer }: AnswerDisplayProps) {
  return (
    <div className="bg-white rounded-xl shadow-sm border overflow-hidden">
      {/* Header with verification badge */}
      <div className="bg-green-50 border-b border-green-200 px-6 py-4">
        <div className="flex items-center space-x-2">
          <CheckCircle className="w-5 h-5 text-green-600" />
          <span className="font-semibold text-green-900">Verified Answer</span>
          <span className="text-xs text-green-700 bg-green-100 px-2 py-1 rounded">
            Cryptographically Signed
          </span>
        </div>
      </div>

      {/* Question */}
      <div className="px-6 py-4 border-b">
        <h3 className="text-sm font-medium text-gray-500 mb-2">Your Question</h3>
        <p className="text-gray-900">{answer.question}</p>
      </div>

      {/* Answer */}
      <div className="px-6 py-4 border-b">
        <h3 className="text-sm font-medium text-gray-500 mb-2">Answer</h3>
        <p className="text-gray-900 leading-relaxed">{answer.answer}</p>
      </div>

      {/* Metadata */}
      <div className="px-6 py-4 bg-gray-50 space-y-3">
        <div className="flex items-start space-x-3">
          <Shield className="w-4 h-4 text-gray-500 mt-0.5" />
          <div className="flex-1 min-w-0">
            <p className="text-xs font-medium text-gray-500">Signature</p>
            <p className="text-xs text-gray-700 font-mono break-all">
              {answer.signature.slice(0, 64)}...
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <Clock className="w-4 h-4 text-gray-500" />
          <div>
            <p className="text-xs font-medium text-gray-500">Timestamp</p>
            <p className="text-xs text-gray-700">
              {new Date(answer.timestamp).toLocaleString()}
            </p>
          </div>
        </div>

        <div className="pt-3 border-t">
          <p className="text-xs text-gray-600">
            ✅ This answer was generated by a verified oracle node
          </p>
          <p className="text-xs text-gray-600 mt-1">
            ✅ The signature proves the answer authenticity
          </p>
          <p className="text-xs text-gray-600 mt-1">
            ✅ All data remains private on Walrus storage
          </p>
        </div>
      </div>
    </div>
  )
}
